spring.application.name=jobster-backend

spring.datasource.url = jdbc:mysql://localhost:3306/jobster
spring.datasource.username = root
spring.datasource.password = Mokshagna@1



spring.jpa.properties.hibernate.dialate = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update


jwt.secret=7c3a9f2e8b1d5c4a6f9e2b8d1c5a7f3e9b2d6c8a4f7e1b5d9c3a8f2e6b1d4c7
jwt.expiration=86400000